### ISSUE TITLE
Update the landing page for Arrikto Academy with figures and a little design work

### ISSUE THREAD

**Issue by shannonbradshaw** [arrikto/learn-kubeflow#3]
Source is here:
https://github.com/arrikto/learn-kubeflow/blob/main/docs/index.md

Rendered view here:
https://academy.arrikto.com

**Comment by bobuel** [comment]
Per conversation with Jimmy: have agreed to use academy.arrikto.com as the single landing page for both community / beginners and minikf, ekf / intermediate users.
